/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmatlink_CoreJMatLink */

#ifndef _Included_jmatlink_CoreJMatLink
#define _Included_jmatlink_CoreJMatLink
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: threadInitNumber */
#undef jmatlink_CoreJMatLink_MIN_PRIORITY
#define jmatlink_CoreJMatLink_MIN_PRIORITY 1L
#undef jmatlink_CoreJMatLink_NORM_PRIORITY
#define jmatlink_CoreJMatLink_NORM_PRIORITY 5L
#undef jmatlink_CoreJMatLink_MAX_PRIORITY
#define jmatlink_CoreJMatLink_MAX_PRIORITY 10L
#undef jmatlink_CoreJMatLink_idleI
#define jmatlink_CoreJMatLink_idleI 0L
#undef jmatlink_CoreJMatLink_engOpenI
#define jmatlink_CoreJMatLink_engOpenI 1L
#undef jmatlink_CoreJMatLink_engCloseI
#define jmatlink_CoreJMatLink_engCloseI 2L
#undef jmatlink_CoreJMatLink_engEvalStringI
#define jmatlink_CoreJMatLink_engEvalStringI 3L
#undef jmatlink_CoreJMatLink_engGetScalarI
#define jmatlink_CoreJMatLink_engGetScalarI 4L
#undef jmatlink_CoreJMatLink_engGetVariableI
#define jmatlink_CoreJMatLink_engGetVariableI 5L
#undef jmatlink_CoreJMatLink_engPutVariableI
#define jmatlink_CoreJMatLink_engPutVariableI 6L
#undef jmatlink_CoreJMatLink_engOutputBufferI
#define jmatlink_CoreJMatLink_engOutputBufferI 7L
#undef jmatlink_CoreJMatLink_engGetOutputBufferI
#define jmatlink_CoreJMatLink_engGetOutputBufferI 8L
#undef jmatlink_CoreJMatLink_destroyJMatLinkI
#define jmatlink_CoreJMatLink_destroyJMatLinkI 10L
#undef jmatlink_CoreJMatLink_engOpenSingleUseI
#define jmatlink_CoreJMatLink_engOpenSingleUseI 11L
#undef jmatlink_CoreJMatLink_engSetVisibleI
#define jmatlink_CoreJMatLink_engSetVisibleI 12L
#undef jmatlink_CoreJMatLink_engGetVisibleI
#define jmatlink_CoreJMatLink_engGetVisibleI 13L
#undef jmatlink_CoreJMatLink_THREAD_DEAD
#define jmatlink_CoreJMatLink_THREAD_DEAD 0L
#undef jmatlink_CoreJMatLink_THREAD_STARTING
#define jmatlink_CoreJMatLink_THREAD_STARTING 1L
#undef jmatlink_CoreJMatLink_THREAD_RUNNING
#define jmatlink_CoreJMatLink_THREAD_RUNNING 2L
#undef jmatlink_CoreJMatLink_THREAD_DYING
#define jmatlink_CoreJMatLink_THREAD_DYING 3L
/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engTestNATIVE
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmatlink_CoreJMatLink_engTestNATIVE
  (JNIEnv *, jobject);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engOpenNATIVE
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jmatlink_CoreJMatLink_engOpenNATIVE
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engOpenSingleUseNATIVE
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jmatlink_CoreJMatLink_engOpenSingleUseNATIVE
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engCloseNATIVE
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jmatlink_CoreJMatLink_engCloseNATIVE
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engSetVisibleNATIVE
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_jmatlink_CoreJMatLink_engSetVisibleNATIVE
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engGetVisibleNATIVE
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jmatlink_CoreJMatLink_engGetVisibleNATIVE
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engEvalStringNATIVE
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jmatlink_CoreJMatLink_engEvalStringNATIVE
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engGetScalarNATIVE
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_jmatlink_CoreJMatLink_engGetScalarNATIVE
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engGetVariableNATIVE
 * Signature: (JLjava/lang/String;)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_jmatlink_CoreJMatLink_engGetVariableNATIVE
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engPutVariableNATIVE
 * Signature: (JLjava/lang/String;[[D)V
 */
JNIEXPORT void JNICALL Java_jmatlink_CoreJMatLink_engPutVariableNATIVE
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engOutputBufferNATIVE
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jmatlink_CoreJMatLink_engOutputBufferNATIVE
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    engGetOutputBufferNATIVE
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmatlink_CoreJMatLink_engGetOutputBufferNATIVE
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jmatlink_CoreJMatLink
 * Method:    setDebugNATIVE
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jmatlink_CoreJMatLink_setDebugNATIVE
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
